This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file ./se-ba-vorlage-14sea.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file se-ba-vorlage-14sea.acn....done (7 entries accepted, 0 rejected).
Sorting entries....done (17 comparisons).
Generating output file se-ba-vorlage-14sea.acr....done (9 lines written, 0 warnings).
Output written in se-ba-vorlage-14sea.acr.
Transcript written in se-ba-vorlage-14sea.alg.
